### ISSUE TITLE
session problemi

### ISSUE THREAD

**Issue by mudinc** [bitnami/bitnami-docker-python#1]
Exception: Session value must be set in /app/myapp/application/models/User.php:73 Stack trace: #0 /app/myapp/application/models/User.php(91): User->is_logged_in() #1 /app/myapp/application/controllers/Result.php(84): User->get_user_id() #2 /app/myapp/application/controllers/Result.php(50): Result->write_answers(NULL) #3 /app/myapp/system/core/CodeIgniter.php(532): Result->index() #4 /app/myapp/index.php(315): require_once('/app/myapp/syst...') #5 {main}

**Comment by juan131** [comment]
Hi @mudinc 

Could you please add more information about how to reproduce the issue?

 - Are you using the `docker-compose.yml` file?
 - What commands did you run when you found the issue?
 - Are you following any guide or documentation?
 - Are you using this Docker Image or a PHP one?

**Comment by ibnbay00** [comment]
Error when upgrade setuptools

FileNotFoundError: [Errno 2] No such file or directory: '/opt/bitnami/python/lib/python3.6/site-packages/setuptools-23.0.0-py3.6.egg'
