### ISSUE TITLE
cant import lzma

### ISSUE THREAD

**Issue by beac0n** [bitnami/bitnami-docker-python#11]
**Description**

import lzma is not working - LZMA package is not usable

**Steps to reproduce the issue:**

1. import lzma

**Describe the results you received:**

```
>>> import lzma
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/bitnami/python/lib/python3.7/lzma.py", line 27, in <module>
    from _lzma import *
ModuleNotFoundError: No module named '_lzma'
```

**Describe the results you expected:**

```
>>> import lzma
```

**Used commands**

`docker run -it bitnami/python ` - error does occur
`docker run -it bitnami/python:3.7-debian-10` - error does occur

`docker run -it bitnami/python:3.7-ol-7-prod` - error **DOES NOT** occur

Seems like an issue with the debian image.
I can't use the oracle image because of https://github.com/bitnami/bitnami-docker-python/issues/10

Installing `liblzma-dev` does **not** fix the issue.

**Comment by dani8art** [comment]
Hi @beac0n, Thank you for reporting this issue, I can confirm that it happens. I'm trying to figure out the root cause and giving a solution.

Regards.

**Comment by dani8art** [comment]
Hi @beac0n, We've just released a new revision of the images fixing this issue, could you pull the latest versions for those rolling tags and try them again, please?

Don't hesitate to Let's know if you have any other issues.

**Comment by beac0n** [comment]
`docker run -it bitnami/python` - error **DOES NOT** occur
`docker run -it bitnami/python:3.7-debian-10` - error **DOES NOT** occur
`docker run -it bitnami/python:3.7-ol-7-prod` - error **DOES NOT** occur

issue is fixed :-)
