### ISSUE TITLE
Update setuptools for Python 3.10

### ISSUE THREAD

**Issue by dominik-bln** [bitnami/bitnami-docker-python#17]
**Description**

When updating to the 3.10 version of this image we are seeing issues like the following:

`pkg_resources.DistributionNotFound: The 'cached-property; python_version < "3.8"' distribution was not found and is required by kombu`

Which seems to be caused by an issue with `setuptools` that has been fixed in a newer version (i. e. it works with standard Python 3.10 docker image and when updating `setuptools==59.5.0`)

**Steps to reproduce the issue:**

This fails:

```dockerfile
FROM bitnami/python:3.10-prod

RUN pip install celery==5.2.1 flower==1.0.0

CMD ["/opt/bitnami/python/bin/celery", "flower"]
```

while this works:

```dockerfile
FROM bitnami/python:3.10-prod

RUN pip install setuptools==59.5.0

RUN pip install celery==5.2.1 flower==1.0.0

CMD ["/opt/bitnami/python/bin/celery", "flower"]
```

**Describe the results you received:**

Flower fails to start.

**Describe the results you expected:**

Flower starts properly

**Additional information you deem important (e.g. issue happens only occasionally):**

Default `setuptools` version in the image is `46.4.0` from May 17th 2020.

**Comment by dominik-bln** [comment]
FYI I'm opening this here because I believe this will likely hit other people on `3.10` in other ways. It looks like some kind of version comparison issue that setuptools had in the past, i. e. either it was not prepared for python 3.10 or did some naive string comparison where `"3.10" < "3.8"` evaluated to `true`. I couldn't find a particular issue or commit though.

**Comment by dominik-bln** [comment]
This seems to explain why updating `setuptools` helps:

https://github.com/pypa/twine/issues/724#issuecomment-753525895

**Comment by marcosbc** [comment]
Hi @dominik-bln, unfortunately I'm unable to reproduce your issue:

```
$ docker build -t  mypython --progress=plain --no-cache .
#1 [internal] load build definition from Dockerfile
#1 sha256:aafb6e6617483f4a1c91eba023f3a24318631c36f26ece04b170c9479f69ee2e
#1 transferring dockerfile: 37B done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 sha256:9573d7dd925d0cb5b64e87ee870d475b23f6c22c9b40e65c80fc9a5bdde6096e
#2 transferring context: 2B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/bitnami/python:3.10-prod
#3 sha256:6f0321e00b9058b41bb6bc766ef4b0547c5ee43f5b1b7167537644eadf287b5c
#3 DONE 0.0s

#4 [1/2] FROM docker.io/bitnami/python:3.10-prod
#4 sha256:154fee18c59c2f1c36c698a9d09c33d9f0f9a1a451eb092d7b78034d84783dee
#4 CACHED

#5 [2/2] RUN pip install celery==5.2.1 flower==1.0.0
#5 sha256:884b400aff35731380b7b63564ccbfa08e8c13314994dcf0b3695368b27fafa8
#5 1.019 Collecting celery==5.2.1
#5 1.058   Downloading celery-5.2.1-py3-none-any.whl (404 kB)
#5 1.110 Collecting flower==1.0.0
#5 1.115   Downloading flower-1.0.0-py2.py3-none-any.whl (457 kB)
#5 1.227 Collecting click-didyoumean>=0.0.3
#5 1.232   Downloading click_didyoumean-0.3.0-py3-none-any.whl (2.7 kB)
#5 1.291 Collecting billiard<4.0,>=3.6.4.0
#5 1.295   Downloading billiard-3.6.4.0-py3-none-any.whl (89 kB)
#5 1.398 Collecting kombu<6.0,>=5.2.2
#5 1.404   Downloading kombu-5.2.2-py3-none-any.whl (188 kB)
#5 1.450 Collecting vine<6.0,>=5.0.0
#5 1.454   Downloading vine-5.0.0-py2.py3-none-any.whl (9.4 kB)
#5 1.508 Collecting click<9.0,>=8.0
#5 1.512   Downloading click-8.0.3-py3-none-any.whl (97 kB)
#5 1.546 Collecting click-plugins>=1.1.1
#5 1.550   Downloading click_plugins-1.1.1-py2.py3-none-any.whl (7.5 kB)
#5 1.698 Collecting pytz>0.dev.0
#5 1.703   Downloading pytz-2021.3-py2.py3-none-any.whl (503 kB)
#5 1.723 Requirement already satisfied: setuptools in /opt/bitnami/python/lib/python3.10/site-packages/setuptools-46.4.0-py3.10.egg (from celery==5.2.1) (46.4.0)
#5 1.752 Collecting click-repl>=0.2.0
#5 1.756   Downloading click_repl-0.2.0-py3-none-any.whl (5.2 kB)
#5 1.812 Collecting humanize
#5 1.816   Downloading humanize-3.13.1-py3-none-any.whl (98 kB)
#5 1.861 Collecting prometheus-client>=0.8.0
#5 1.865   Downloading prometheus_client-0.12.0-py2.py3-none-any.whl (57 kB)
#5 1.966 Collecting tornado<7.0.0,>=5.0.0
#5 1.972   Downloading tornado-6.1.tar.gz (497 kB)
#5 2.081   Preparing metadata (setup.py): started
#5 2.532   Preparing metadata (setup.py): finished with status 'done'
#5 2.663 Collecting prompt-toolkit
#5 2.671   Downloading prompt_toolkit-3.0.24-py3-none-any.whl (374 kB)
#5 2.685 Requirement already satisfied: six in /opt/bitnami/python/lib/python3.10/site-packages/six-1.16.0-py3.10.egg (from click-repl>=0.2.0->celery==5.2.1) (1.16.0)
#5 2.767 Collecting amqp<6.0.0,>=5.0.6
#5 2.771   Downloading amqp-5.0.7-py3-none-any.whl (50 kB)
#5 2.831 Collecting wcwidth
#5 2.835   Downloading wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
#5 2.876 Using legacy 'setup.py install' for tornado, since package 'wheel' is not installed.
#5 3.043 Installing collected packages: wcwidth, vine, prompt-toolkit, click, amqp, pytz, kombu, click-repl, click-plugins, click-didyoumean, billiard, tornado, prometheus-client, humanize, celery, flower
#5 3.938     Running setup.py install for tornado: started
#5 4.758     Running setup.py install for tornado: finished with status 'done'
#5 5.249 Successfully installed amqp-5.0.7 billiard-3.6.4.0 celery-5.2.1 click-8.0.3 click-didyoumean-0.3.0 click-plugins-1.1.1 click-repl-0.2.0 flower-1.0.0 humanize-3.13.1 kombu-5.2.2 prometheus-client-0.12.0 prompt-toolkit-3.0.24 pytz-2021.3 tornado-6.1 vine-5.0.0 wcwidth-0.2.5
#5 5.249 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#5 DONE 5.7s

#6 exporting to image
#6 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
#6 exporting layers
#6 exporting layers 0.3s done
#6 writing image sha256:939ab198c6811a4d0726cefca53ec3968f5a47f1efe66b5108d5a20aebe0e44a done
#6 naming to docker.io/library/mypython done
#6 DONE 0.3s
```

As you can see, the packages are installed without issues.

**Comment by dominik-bln** [comment]
Ah sorry, I should have clarified that the problem happens when starting the container not during the build.

`celery` and flower seem to somehow use setuptools during startup (seems a bit odd I know)

**Comment by dominik-bln** [comment]
Here are the docs from Celery explaining the behaviour:

https://docs.celeryproject.org/en/stable/userguide/extending.html#adding-new-celery-sub-commands

**Comment by marcosbc** [comment]
It seems like there might be an issue with the Pip dependency resolver here, as it should be installing the proper dependency for setuptools with `celery==5.2.1 flower==1.0.0`, not sure if there is anything we can do in Bitnami to that.

**Comment by dominik-bln** [comment]
As far as I can tell `pip` is ok here, but the celery plugin install invokes `setuptools` behind the scenes and the problematic `setuptools` version is the one that comes preinstalled with the image.

I still feel like that version should be updated if possible because it has an [issue](https://github.com/pypa/twine/issues/724#issuecomment-753525895) with Python `3.10`. Particularly it looks like it does some naive string comparison where `"3.10" < "3.5"` evaluates to `True`. And while the Celery issue might not be the most common use-case, I expect other people to run into similar problems whenever setuptools gets invoked without being updated first.

I don't really understand where the Python binaries distributed with this image are coming from or if you have control over them, but when comparing vanilla python docker image with the bitnami version, the setuptools version is really outdated:

```bash
~  % docker run --platform linux/amd64 -it python:3.10 pip list | grep setuptools                                             [17:25:13]
setuptools 57.5.0
~  % docker run --platform linux/amd64 -it bitnami/python:3.10-prod pip list | grep setuptools                                [17:50:50]
setuptools                        46.4.0
```

So if you have the means to update that, I think you will safe other people some grief and maybe also lessen the support burden when more people update to `3.10`. Feel free to close though if that is not really possible, the workaround to update `setuptools` on our side is easy enough.

**Comment by marcosbc** [comment]
Hi @dominik-bln, in that case maybe it would make sense to open a new ticket for the Celery package, in order to declare a specific setuptools version as a minimum dependency, to avoid issues like these.

In the meantime, I've opened an internal ticket for updating etuptools to a newer release. However, I'm unfortunately unable to provide any ETA for when that fix would be available.

**Comment by dominik-bln** [comment]
True, I'll see what I can do there. Thanks for your time on this matter so far.

**Comment by dominik-bln** [comment]
It seems someone else also noticed the problem on the Celery side before I got around to opening a ticket there. The latest version of Celery includes a version range for setuptools:

https://github.com/celery/celery/blob/f816e1cc2c61f9c300c1d8c50d4ff996c125f249/requirements/default.txt#L9

**Comment by leiserfg** [comment]
It affects any project using `pkg_resources`, that's stopping me to use this image.

**Comment by leiserfg** [comment]
I'm doing:
`RUN pip install "setuptools>=60"`
as a workaround.

**Comment by rafariossaa** [comment]
Hi,
  Thanks for providing a workaround.
