### ISSUE TITLE
Adding Github container registry

### ISSUE THREAD

**Issue by zrothberg** [bitnami/bitnami-docker-python#19]
Would it be possible to add an extra deployment to the github container registry? As far as I can tell you have deployments on basically every other container registry and this would be helpful for creating github actions or ci/cd stuff and being able to match containers from aws.

**Comment by javsalgar** [comment]
Hi! Thanks for the feedback. I will forward this to the team for consideration. However, there are no short or mid-term plans to extend the platforms where we publish our containers. In case this changes, we will let the community know.
