### ISSUE TITLE
Apple Silicon / M1 Support

### ISSUE THREAD

**Issue by twopirllc** [bitnami/bitnami-docker-python#22]
### Name and Version

bitnami/python:3.10

### What is the problem this feature will solve?

To include and support Apple Silicon architectures. 😎 

Thanks for the consideration.

### What is the feature you are proposing to solve the problem?

Support Apple Silicon and Improve performance.

### What alternatives have you considered?

Other Python Docker images.

**Comment by carrodher** [comment]
Hi, we have created this issue https://github.com/bitnami/charts/issues/7305 that is pinned in the Bitnami Helm Charts repository, on this way we can funnel all the conversation in a single place regarding ARM64 support.

We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any new (when possible) about this topic.

**Comment by twopirllc** [comment]
@carrodher,

Great! Thank you! I appreciate it.

Kind Regards,
KJ
